- .gitignore
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
Update add command to feature the new fields - course and friendship
Update edit command to feature the new fields - course and friendhip
Update UI to reflect the changes
Update tests to reflect the changes in the fields
> Update add command v1

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/model/person/Friendship.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Add Edit command
Improve Add command
Update tests and data to match
> Update edit command

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/backend/AutoUpdatePerson.java
- src/main/java/seedu/address/model/person/Course.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Modified Main app to compare current date time
Created new folder and file in logic folder to automatic update the person previous and current sem module once sem ended
Modified logic manager to save the updated details into json file
Addes new person constructor with " prev courses" field
Modified jsonadaptedperson so the json data have previous courses field
Modified the jsonadaptedpersontest so that the test cases can test the new field
To know if it works can modify the laptop time e.g. change to 2026 , Once time past the current sem
If prev course is nil, it will be updated to the current sem course
If prev course has something, the current mod will be added on
> Update the functionality of the archive function

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
- Improve tag layout by aligning all tags side by side for better organization
> Update Ui for name card tag

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/backend/AutoUpdatePerson.java
- src/main/java/seedu/address/model/LoginBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/storage/JsonLoginBookStorage.java
- src/main/java/seedu/address/storage/JsonSerializableLoginBook.java
- src/main/java/seedu/address/storage/LoginBookStorage.java
- src/main/java/seedu/address/storage/Storage.java
- src/main/java/seedu/address/storage/StorageManager.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/DateCheckTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
- Created the "Click to Expand" button which will only show the recent 5 courses in the previous courses field and all previous courses once expanded.
- Created a Last Login function to accurately check Semester End by saving and retrieving from a json file
Reason: If user does not logon for a long period of time e.g. 1 year, the Check Sem ended will have inaccuracy using rhe logic e.g. if last login was 3/3/2025, current login is 3/3/2026, the  logic would have inaccurately set the semester end date to 31/5/2026 and indicate that semester has not end which is inaccurate since it should have ended 1 year ago, thus created this last login to more accurately track and check if semester has ended. If last login is before the current semester start date , update the courses
- Created Test …
> Create last login & update archive function

- src/main/java/seedu/address/logic/backend/AutoUpdatePerson.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- Modified object type from List to LinkedHashSet to prevent duplicates
- Modified such that even when there is duplicate in json file due to manual insertion, the duplicates wont be shown
> Fix duplicate issue

- docs/diagrams/LogicClassDiagram.puml
Modify logic class diagram to include AutoUpdatePerson
> Modify logic class diagram

- docs/diagrams/BetterModelClassDiagram.puml
- Update multiplicity for Person to Tag in better model class diagram
- Add Course class
- Add PreviousCourse class
- Add Friendship class
> Update model class diagram

- build.gradle
- src/main/java/seedu/address/logic/backend/AutoUpdatePerson.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
Based on TP progress dashboard, our team repo's build.gradle need to include assertion.
> Add assertion

- docs/DeveloperGuide.md
- docs/diagrams/ModelClassDiagram.puml
- src/main/java/seedu/address/model/ModelManager.java
Only sort when `find` command is called. All other commands retain original ordering.
> Refine find command

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
Modify the Find command error message to reflect most updated format
Modify find logic  to fix the error i brought up in issue
> Fix Find function

- src/main/java/seedu/address/logic/Messages.java
Modify return message for add command to display course value in course tag instead of previous course tag
> Modify return message for add command

- src/main/java/seedu/address/model/course/Course.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/person/PreviousCourse.java
- src/main/java/seedu/address/model/tag/Tag.java
Course and Previous format: alphanumeric and a maximum of 10 characters long. It must also follow a structured format: a department code (letters) followed by a course number (digits), with an optional single-letter suffix. e.g. CS2030S, CFG1003
Tags: Alphanumeric , maximum 20 characters
Phone: update description to mentioned max 15 characters
> Update Regex and its explaination

- docs/DeveloperGuide.md
Update developer guide to use correct terms
> Modify developer guide

- docs/index.md
Modify index page to use correct terms
> Modify index page

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
Fixes bug when editing a contact, the previous course data is lost
> Edit prev courses

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
Changed Error message from "person" to "friend"
Changed "Addressbook" to "NUSMeet"
> Edit message

- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Modify phone number regex to allow optional + sign
> Modify phone number regex

- docs/UserGuide.md
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/ui/MainWindow.java
Solve the issue where help window is unable to open with help command after minimize
Update user guide
Update name error message
> Update to restore help window when minimize

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/BetterModelClassDiagram.puml
- src/main/java/seedu/address/model/person/Phone.java
Update User Guide
Update Developer Guide
Update the phone error message
> Solve minor change
